# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ESP4HA
version: "1.1.0"
slug: esp4ha
description: EskomSePush for Homeassistant
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

options:
  ESP_API_KEY: "D1A16BDC-341C4F37-9CBDDD05-9B90E845"
  YOUR_AREAD_ID: "tshwane-16-doornpoort"
  HA_LongLiveToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxZDkyNThkYjYxNWI0NTk5YTFlODdjMDk3OTNmNGVkZSIsImlhdCI6MTcwNDQ3Mjk1NiwiZXhwIjoyMDE5ODMyOTU2fQ.Ru5jxXuoUqD09lC84hgXMOe0FkIS5dmsMES-ECFezbs"
  Home_Assistant_IP: "192.168.1.8"
  HTTP_Connect_Type: "http"
  Home_Assistant_PORT: "8123"
  Refresh_rate: 1800  

  
schema:
  ESP_API_KEY: password
  YOUR_AREAD_ID: str
  HA_LongLiveToken: password
  Home_Assistant_IP: str
  HTTP_Connect_Type: str
  Home_Assistant_PORT: str
  
  Refresh_rate: int
  
