# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ESP4HA
version: "1.1.0"
slug: esp4ha
description: EskomSePush for Homeassistant
url: "https://github.com/martinville/esp4ha"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

options:
  ESP_API_KEY: ""
  YOUR_AREAD_ID: ""
  HA_LongLiveToken: ""
  Home_Assistant_IP: "https://github.com/martinville/esp4ha"
  HTTP_Connect_Type: "http"
  Home_Assistant_PORT: "8123"
  Refresh_rate: 1800  

  
schema:
  ESP_API_KEY: password
  YOUR_AREAD_ID: str
  HA_LongLiveToken: password
  Home_Assistant_IP: str
  HTTP_Connect_Type: str
  Home_Assistant_PORT: str
  
  Refresh_rate: int
  
